### ISSUE TITLE
Optionally open EditorVR automatically

### ISSUE THREAD

**Issue by leith-bartrich** [Unity-Technologies/EditorXR#143]
In the future, I'd expect the need to arise, to open UnityEditor directly into a VR Editing mode.  Which in turn may mean launching the editor in a kind of "headless" mode and launching VRView with the default editing context.

Probably, launching VRView automatically is more important than a headless mode.  But even the headless mode may become desirable in the future as Mixed Reality platforms become more concretely understood.

Example: Consider running UnityEditor on the Microsoft HoloLens or its successors.  Or one of their new mixed reality VR headsets.  Ideally, you don't launch the program and then launch the VR part of the program.  Rather, you launch the MR program from within MR and it is a MR program.  Or at least, that's probably a long term goal.

Example: If I want to author a "project manager" from within VR, I probably need the ability for UnityEditor to close out the existing project, open the new project, and then run EditorVR immediately.  So I don't have to take off my headset.  I can just issue the command and wait for it.

This is probably a longer term goal.  It's not immediately necessary.  But it's maybe worth keeping on the potential horizon.

**Comment by mtschoen-unity** [comment]
I had actually thought about adding a shortcut to the SteamVR menu for EditorVR, which would also require this kind of thing. A single desktop shortcut for "Start EditorVR" would also be nice. We'll probably add a command line argument or some other way to externally signal Unity to start into EVR or open EVR in a running Unity instance.

**Comment by mtschoen-unity** [comment]
Part of the recent Minimal Context upgrade (#500) was an option to auto-open the VR View when the user puts on the HMD. Is this what you were looking for? If so, feel free to come back and close this issue. You may also be interested in the play/player update (#486) that's part of the 0.2 release.
