### ISSUE TITLE
Move EditorVR to Phase 1 and Phase 2 compilation

### ISSUE THREAD

**Issue by leith-bartrich** [Unity-Technologies/EditorXR#144]
As per: https://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html

EditorVR probably belongs in a combination of Phase 1 and Phase 2 compilation as it is meant to be a very low level editor extension (plugin.)

It might even require a new set of earlier phases, which are guaranteed to be linked into the editor, even if later phases fail to compile.  Such that code errors in later build phases don't break the ability to work on, author, link and use EditorVR extensions.

I often run into the problem that editor extensions stop loading into Unity when I try and resurrect old broken projects.  I often need to replace the editor extensions with newer versions in order to begin to fix the project.  And they won't link in to the editor because the project is broken.  It's a chicken and egg problem where errors in later build phases preclude earlier successful build phases from linking to the editor.

It's probably unacceptable in the long run, for EditorVR to break when the game you're using it on fails to compile.  Since EditorVR is expected to remain an open-source project that is extendable, it's probably not okay to depend on it being deployed as a DLL to get around this problem.

The first step is probably to move it as early as possible in the build phases to reflect its very low level nature.

The second step is probably to address the editor linking issues such that you can guarantee its ability to build and link along with its ecosystem, even when other compilation phases fail.

This issue is unlikely to come up in earnest until EditorVR leaves experimental status.  But I do expect it to be an issue in the long term.  Just as I experience the issue with current editor extensions that I use for code generation and build systems.

**Comment by mtschoen-unity** [comment]
Since Assembly definitions were introduced, individual assemblies per package is now the intended configuration. (#486) updates EditorXR to use assembly definitions.
