### ISSUE TITLE
Undo/redo only appear if object is selected

### ISSUE THREAD

**Issue by timoni** [Unity-Technologies/EditorXR#204]
Really got to fix this

**Comment by amirebrahimi** [comment]
If undo/redo always appear, then the joysticks cannot be used on that hand or for a tool, so what is desired here? Do we remove the ability to select items from the radial menu with the joystick?

**Comment by timoni** [comment]
From my understanding, tools can overwrite the radials. 

Not sure why having undo/redo appear when available would remove ability to select items from the radial; the idea was the radial menu should appear when any actions are available on it. 

It just so happens that most of the available actions appear when an object is selected.

**Comment by amirebrahimi** [comment]
Are you saying that if you have a tool on a hand that uses joysticks that it is okay that the radial menu will not respond to joysticks in that case?

Having undo/redo appear does not preclude selecting items from the radial -- it's that when the radial menu is open that it consumes joystick input.

Re: undo/redo showing when they are available -- essentially they are always available, which means that the radial menu is always on. 

Does that help clarify?

**Comment by timoni** [comment]
Yes. That was the original intended design, but now it's sounding like
maybe we should have undo/redo as a dedicated UI element instead of
attached to the controller or radial.

Cheers,
Timoni

Unity Labs • @timoni <https://twitter.com/timoni> • 415.238.7020

**Comment by timoni** [comment]
Decision: let's remove joystick & controller support from the radial entirely.

**Comment by dunity** [comment]
This has been partially addressed in the following PR : https://github.com/Unity-Technologies/EditorVR/pull/369

**Comment by mtschoen-unity** [comment]
This issue was closed by #407
