### ISSUE TITLE
Each locomotion method needs to handle losing input

### ISSUE THREAD

**Issue by AndrewTHEManeri** [Unity-Technologies/EditorXR#324]
Currently each 'method' in the locomotion tool, if it activates locomotion, prevents the rest of the methods down the chain from firing.  We should switch to a paradigm where the other methods down the chain can be informed that a separate locomotion technique was used, so they can undo any effect or setup they are putting in place.

**Comment by mtschoen-unity** [comment]
I wouldn't call it "losing input" so much as "being overridden." This makes me think you would like to solve the issue by consuming controls. That said, it could be easier to think of LocomotionTool as a set of tools that can be added removed (i.e. remove Fly and add Blink, leave Crawl on all the time)
