### ISSUE TITLE
Add Windows Mixed Reality support

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-Technologies/EditorXR#462]
Started a new Feature branch (#461) to work on native Windows Mixed Reality support

Can get EditorVR working under SteamVR (not OpenVR? with no Steam SDK installed)

However, even will all the necessary components implemented:

- WindowsMRProxy
- WindowsMRInputToEvents
- WindowsMR Affordance
- Updated EditorVR & VrView scripts to recognise UWP

The scene won't start:

* Controllers will not visualise
* EditorVR window keeps crashing.

Help Appreciated.

**Comment by DDReaper** [comment]
yeah, submitted the PR to create a new feature branch to help work on this.
Only thing missing (apart from it not working) is support for the gLTF models for the controllers, but that can wait until it's at lease running :D

**Comment by DDReaper** [comment]
FYI, I also noted the same issues with WindowsMR also exist if you try OpenVR in Unity without the SteamVR plugin installed.

**Comment by SimonDarksideJ** [comment]
Any update on this @mtschoen-unity ?

**Comment by mtschoen-unity** [comment]
Hi there! I should have closed this ticket when I closed the PR. It is possible that we may circle back to Windows Mixed Reality later on, but it is not on the roadmap for this time. The plan is to eventually update to the new input system, which should make it easier to support new platforms going forward.
