### ISSUE TITLE
Are there additional EditorXR friendly UnityEngine.CoreModule files?

### ISSUE THREAD

**Issue by NextWorldVR** [Unity-Technologies/EditorXR#470]
Hello!  Thank you for EditorXR,  TRULY AMAZING TOOL. There are no adequate words...  

On the EditorXR 'undo problem', I am not sure I fully understand the problem, but where it is mentioned: https://docs.google.com/document/d/1xWunGC3NJoDRBBz44gxpMUAh3SmedtNK12LqACyy2L0/edit#

it is mentioned with only a single file available. (is this the only one or are there more?)

My question:  can the one listed:  
''UnityEngine.CoreModule_2017.3.0f3.zip''
be used on Unity 2017.3.0p3 ?  I suspect it will strip the Pro functionality.

If not, is there one for

 (ideally):  Unity 2017.3.1p2

or barring that:  Unity 2017.3.0p3

Making a barebones EDITOR XR User Layout in Unity was such a good idea, I had Game and Scene open on two different monitors and was STILL having pretty good luck running Netflix on DASH window while Editing in Editox XR like when I work in MEDIUM! :)  I can't wait to see how well it works when I am fully optimized.   Editor XR more than any other thing ever, makes me want to have the best computer I possibly can  LOL  :)  :)  THAT IS DEFINATELY A COMPLMENT!!

THANK YOU!  
Robert

**Comment by mtschoen-unity** [comment]
Hello there.

Thanks for your complimentary words. The Undo Patch issue has been officially resolved as of Unity 2018.2. We have provided a patch for 2018.1, but highly recommend users update to the latest version of Unity for the latest versions of EditorXR.

I will close this issue for now, but if there is still a need for the undo patch on 2017.3.1 or some older version of Unity, let us know and we will try to accommodate. Remember, the patch is not necessary for undo to work, only redo.
