### ISSUE TITLE
SteamVR_Controller does not exist in this context

### ISSUE THREAD

**Issue by damonbla** [Unity-Technologies/EditorXR#501]
Using Unity 2018.2.7f1 and SteamVR Unity Plugin 2.0.1.

Imported the Editor VR asset from the download in the readme and the SteamVR asset from the Asset Store. Loaded the SteamVR "Simple Sample" scene. I get the following error five times in the file ViveInputToEvents.cs:

Assets/EditorVR/Scripts/Input/ViveInputToEvents.cs(63,40): error CS0103: The name `SteamVR_Controller' does not exist in the current context

The error pops up for every mention of that variable. And this error once in the same file:

Assets/EditorVR/Scripts/Input/ViveInputToEvents.cs(84,93): error CS0172: Type of conditional expression cannot be determined as `<error>' and `<error>' convert implicitly to each other

I thought it might have been a compile order problem at first thanks to a Google search, but that does not seem to be the issue. It appears Valve removed "SteamVR_Controller" altogether in the 2.0 version of the plugin, or changed the name to something else, because when I search the code in Visual Studio for it I get nothing in the code.

**Comment by chatrat12** [comment]
Try 2014.4 LTS. 2018 is not currently supported.
https://forum.unity.com/threads/psa-current-supported-unity-release-for-editorxr-is-2017-4-lts.532486/

**Comment by amirebrahimi** [comment]
SteamVR plugin version 2.0 and later is not supported yet. You have to use the older plugin version:
https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/1.2.3
