### ISSUE TITLE
[Doc issue] 2018 not supported is not documented.

### ISSUE THREAD

**Issue by chatrat12** [Unity-Technologies/EditorXR#502]
Wasted a bit of time trying to get EXR to work. Doc says `Launch Unity 2017.2p2 or later'. After messing with it for over an hour, I came across this post:
https://forum.unity.com/threads/psa-current-supported-unity-release-for-editorxr-is-2017-4-lts.532486/

It's probably obvious to everyone tracking the progress of EXR, but not to people who are getting into it just now. Could save some other newbies quite a bit of time knowing that 2018 doesn't work out of the box :)

**Comment by amirebrahimi** [comment]
Thank you for this. I've updated the docs, the link to point to 2017.4 LTS, and also the SteamVR plugin link in the docs.
