### ISSUE TITLE
KeyNotFoundException / MissingReferenceException

### ISSUE THREAD

**Issue by psarras** [Unity-Technologies/EditorXR#523]
Hi,

I am trying to play with the EditorXR but I am getting the following errors:

![image](https://user-images.githubusercontent.com/3820417/53099349-8993cf80-351d-11e9-8347-482054de5388.png)

I have attempted with different Unity version starting from 2017.2 onwards. on 2019 I had to edit a few deprecated functions but on all of them I get the same errors. Is there a known combination that works? I looked at the docs and they say anything above 2017.2 should work, but that hasn't been my experience so far. :(

**Comment by mtschoen-unity** [comment]
Hi there! Thanks for reporting this issue. I'm not familiar with this particular error but some of the others in this screenshot look familiar. If you are getting the code to compile, you should either see warnings about a missing dependency, or everything should work fine.

It seems that you posted this issue before our 0.2 release. Could you try that version and see if your issues persist? The best version of Unity to use is 2018.3.x. It is usually easiest to import via the release package, but if you clone the latest development branch and import the `Dependencies_asmdef` package (See the (Getting Started Guide)[https://docs.google.com/document/d/1RD0SAjWnXdtY6eOC4qHk_fcl7w2-aBGrF3rX5pk5KDo/edit]) you should be all set.

Let us know how it goes!

**Comment by guoguoguilai** [comment]
> Hi,
> 
> I am trying to play with the EditorXR but I am getting the following errors:
> 
> ![image](https://user-images.githubusercontent.com/3820417/53099349-8993cf80-351d-11e9-8347-482054de5388.png)
> 
> I have attempted with different Unity version starting from 2017.2 onwards. on 2019 I had to edit a few deprecated functions but on all of them I get the same errors. Is there a known combination that works? I looked at the docs and they say anything above 2017.2 should work, but that hasn't been my experience so far. :(

If you check the option that runs in runtime, add a camera, and you will find those errors dispear.
