### ISSUE TITLE
Valve Index & knuckles controllers support?

### ISSUE THREAD

**Issue by Oyshoboy** [Unity-Technologies/EditorXR#564]
Hello!
I would like to know, are there Valve Index & knuckles controllers support are planned?

**Comment by amirebrahimi** [comment]
Our current focus is getting EditorXR turned into a package that will show up in the Package Manager. After that we'll look at a variety of support requests that have come in lately. To anyone else reading this: PRs are welcome if someone wants to add this support before we get to it.

**Comment by Oyshoboy** [comment]
Thank you @amirebrahimi
