### ISSUE TITLE
Update README to provide basic overview and instructions

### ISSUE THREAD

**Issue by rlaferla** [Unity-Technologies/EditorXR#573]
I would like to try EditorXR but the README doesn't have an overview never mind basic instructions.

This GitHub repository is linked to the Get Started button on this page so one would expect to find some basic instructions:

https://unity.com/editorxr

Questions I have that could be answered in the README or the comments below:

1.  Is this project active?  Does it work with latest 2020 release of Unity?
2.  Does it work on macOS?
3.  Does it work with Oculus Quest 2?
4.  How to build and install it?  Is there a precompiled version somewhere?

I would love to edit my scenes using my Oculus Quest 2.  It would make development go faster and easier...

**Comment by lufinkey** [comment]
Found some instructions from [this forum](https://forum.unity.com/threads/am-i-too-stupid-to-install-editorxr-solved-step-by-step-guide.994603/) thankfully and was able to install it. Still haven't been able to figure out how to run it though. I'm on macOS as well.

**Comment by lufinkey** [comment]
My guess is that macOS is not supported, given that I can't find any of the things described by the readme. I may just also be on too new of a version.

**Comment by rlaferla** [comment]
I couldn’t get it to work on Windows 10 either and haven’t bothered to try again in months.

**Comment by amirebrahimi** [comment]
> I would like to try EditorXR but the README doesn't have an overview never mind basic instructions.

It looks like we lost the front page README when we converted this repo to an actual Unity package. The original instructions are here: https://github.com/Unity-Technologies/EditorXR/blob/main/Documentation~/com.unity.labs.editorxr.md

> This GitHub repository is linked to the Get Started button on this page so one would expect to find some basic instructions:
> 
> https://unity.com/editorxr

This is a miss on our part. Thanks for pointing it out. Perhaps a quick fix is simply to point it to the link I posted above.

> Questions I have that could be answered in the README or the comments below:
> 
> 1. Is this project active?  Does it work with latest 2020 release of Unity?

We're working on the successor to EditorXR in spirit, but it may undergo a 

> 2. Does it work on macOS?

It may run, but with the state of VR on macOS I'm not sure how well it would. I don't think Oculus works any more and perhaps the Vive does, but I haven't tested that personally.

> 3. Does it work with Oculus Quest 2?

Yes, you can use it with the link cable or over wifi, which treats the Quest 2 as a desktop device.

> 4. How to build and install it?  Is there a precompiled version somewhere?
> 
> I would love to edit my scenes using my Oculus Quest 2. It would make development go faster and easier...

See the link I posted above. You basically just need to add it as a package to your Unity project either with the Git URL or cloning the repo locally into your Packages folder.

**Comment by mtschoen-unity** [comment]
Hey @rlaferla, thanks for submitting this issue!

I've just pushed an update which links to the documentation from the readme, and adds more clarity around setup/install. You can also read more about the update to using the package structure here https://forum.unity.com/threads/editorxr-0-4-available-on-unity-package-manager.978909/

You can also browse the docs and scripting API here https://docs.unity3d.com/Packages/com.unity.editorxr@0.4/manual/index.html

Hope this helps!
